- import_tasks: debian.yml
  when: ansible_distribution|lower == 'debian'
- import_tasks: centos.yml
  when: ansible_distribution|lower == 'centos'  
- unarchive:
    src: https://hectorvido.dev/site.tar.gz
    dest: /var/www/html
    remote_src: yes
- file:
    path: /var/www/html/index.html
    state: absent
- template:
    src: login.php
    dest: /var/www/html/login.php
    force: yes  
